name: gaudi
channels:
- insilichem
- omnia
- salilab
- bioconda
dependencies:
- python=2.7
- nomkl
- openmm
- openmoltools
- pdbfixer
- cclib
- scipy
- numpy
- imp
- git
- pip:
  - pychimera
  - munch
  - voluptuous
  - click
  - boltons
  - deap
  - pyyaml
  - prody==1.8.2

