export GOLD_DIR="/QFsoft/applic/CCDC/GOLD5.2/GOLD"
export CCDC_LICENSE_FILE="/QFsoft/applic/CCDC/GOLD5.2/ccdc_licence.dat"
export PVM_ROOT="/QFsoft/applic/CCDC/GOLD5.2/GOLD/pvm3"
export PVM_ARCH="LINUX64"
export PATH="/QFsoft/applic/CCDC/GOLD5.2/bin/:/QFsoft/applic/CCDC/GOLD5.2/GOLD/bin/:$PATH"
