# Until prody has a conda recipe, conda-build <= 3.16 is needed
# Requires additional channels:
#   conda build --python=2.7 -c insilichem -c bioconda -c conda-forge -c salilab -c omnia -c "$CONDA_PREFIX/conda-bld/" .

{% set version = environ.get('GIT_DESCRIBE_TAG', 'v')[1:] %}
package:
  name: gaudi
  version: {{ version }}

about:
  home: https://github.com/insilichem/gaudi
  license: Apache
  license_file: LICENSE
  summary: Genetic Algorithms with Unrestricted Descriptors for Intuitive Molecular Modeling

source:
  path: ../
  version: {{ version }}


build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - python 2.7*
    - setuptools
    - distribute
    - numpy

  run:
    # Base dependencies
    - python 2.7*
    - setuptools
    - distribute
    - nomkl
    - munch 2.2*
    - voluptuous 0.10*
    - click 6.7*
    - boltons 17.2*
    - deap 1.2*
    - pyyaml
    - pychimera >=0.2.6
    # Objectives and genes
    - openmm
    - openmoltools
    - pdbfixer
    - cclib
    - scipy
    - imp 2.9*
    # InsiliChem channel
    - autodock-vina
    - autodocktools-prepare
    - prody 1.8.*
    - drugscorex  # [linux]
    # - nwchem  # [linux]

test:
  imports:
    - gaudi
  commands:
    - gaudi -h
    - gaudi run -h
    - cd tests && python run_test.py --benchmark-disable; cd ..
  source_files:
    - tests
  requires:
    - pytest 4.0.*
    - pytest-benchmark

