# Requires additional channels:
#   conda build --python=2.7 -c insilichem -c bioconda -c conda-forge -c salilab -c omnia -c "$CONDA_PREFIX/conda-bld/" .

package:
  name: gaudi
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/gaudi
  license: Apache
  license_file: LICENSE
  summary: Genetic Algorithms with Unrestricted Descriptors for Intuitive Molecular Modeling

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - python 2.7.*

  run:
    # Base dependencies
    - python 2.7.*
    - nomkl
    - munch 2.2.*
    - voluptuous 0.10.*
    - click 6.7.*
    - boltons 17.2.*
    - deap 1.2.*
    - pyyaml
    - pychimera >=0.2.6
    # Objectives and genes
    - openmm
    - openmoltools
    - pdbfixer
    - cclib
    - scipy
    - imp 2.9.*
    - autodock-vina
    # InsiliChem channel
    - autodocktools-prepare
    - prody 1.8.*
    - drugscorex
    # - nwchem  # [linux]

test:
  imports:
    - gaudi
  commands:
    - gaudi -h
    - gaudi run -h
    - cd tests && python run_test.py -v --benchmark-disable; cd ..
  source_files:
    - tests
  requires:
    - pytest 4.0.*
    - pytest-benchmark

