package:
  name: gaudi
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/gaudi
  license: Apache 2.0
  summary: Genetic Algorithms with Unrestricted Descriptors for Intuitive Molecular Modeling

source:
{% if environ.get('TRAVIS') %}
  git_url: ../
{% else %}
  git_url: https://github.com/insilichem/gaudi.git
{% endif %}
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

requirements:
  build:
    - python 2.7*
    - setuptools
    - distribute
    - numpy

  run:
    - python 2.7*
    - setuptools
    - distribute
    - nomkl
    - openmm
    - openmoltools
    - pdbfixer
    - cclib
    - scipy
    - imp
    - autodock-vina
    - autodocktools-prepare
    # - nwchem  # [linux]

test:
  imports:
    - gaudi



